on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Running test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker action step
        uses: ./
        id: docker-runner