on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["ubuntu"]

    steps:
      - name: Get PyIndi Sources
        uses: actions/checkout@v2

      - name: Test PyIndi
        run: |
          /bin/bash run_tests.sh